### ISSUE TITLE
Why using Sidekiq::Worker instead of ActiveJob?

### ISSUE THREAD

**Issue by olivierobert** [Tolsee/google-scrape-api#11]
Rails 4.2 added built-in support for asynchronous jobs via [ActiveJob](https://edgeguides.rubyonrails.org/active_job_basics.html). It provides a unique interface for several backends including Sidekiq.

**Comment by Tolsee** [comment]
The reason I use `Sidekiq::Worker` over `ActiveJob` is as I see this application does not need to change to/add other backend libraries(other than Sidekiq) and `Sidekiq::Worker` is [more performant while pushing jobs to Redis](https://github.com/mperham/sidekiq/wiki/Active-Job#performance). Also, before Sidekiq 6 support for retries on ActiveJob was limited which is not true now, but this style of using `Sidekiq::Worker` came from that as well.

But, yes, ActiveJob can be a good choice when working on real projects where multiple backends may be fruitful.

**Comment by olivierobert** [comment]
Well noted
