### ISSUE TITLE
Keywords response serialization improvements 

### ISSUE THREAD

**Issue by olivierobert** [Tolsee/google-scrape-api#12]
![Google_scrape](https://user-images.githubusercontent.com/696529/64769835-31cebb80-d576-11e9-91fe-b61c102f272d.jpg)

When g=fetching keywords from the API, the attributes for links should not expose the model name because of 1) security concerns (exposing application code) and 2) standardizing responses to use snakecase.

It should instead be `Link::Ad` -> `ad_link_count` and `Link::Result` -> `result_link_count`

**Comment by Tolsee** [comment]
Yes, I totally agree. I am sending a PR for the fix.

**Comment by Tolsee** [comment]
I hope the PR solves the issue.

**Comment by olivierobert** [comment]
I works but since it's based on a class name, maybe the definition of a constant could have been avoided with:

```
type = relation.type.class.name.demodulize
```

**Comment by Tolsee** [comment]
First of all, Sorry for the late reply. 

> type = relation.type.class.name.demodulize

I think it would be something like `relation.class.name.demodulize`. Yes, I agree with you on this.
